### ISSUE TITLE
laravel-mix 6 support dependency issues

### ISSUE THREAD

**Issue by denpet** [wewowweb/laravel-mix-svelte#12]
I think the | should be || in the package.json
current: "laravel-mix": "^4.0 | ^5.0 | ^6.0"
Testing on https://semver.npmjs.com you need to put ^4.0 || ^5.0 || ^6.0 to match either major version.

**Comment by morpheus7CS** [comment]
Hey @denpet,

thanks for reporting it. Fixed it according to what you've written.

Would you mind letting me know if it works now?

Kind regards,
g

**Comment by denpet** [comment]
Works like  charm!

Thanks for quick response

/Dennis
