### ISSUE TITLE
How do we use this?

### ISSUE THREAD

**Issue by nrthbound** [wewowweb/laravel-mix-svelte#21]
Got it installed, no problem. But... there is no documentation on how this is to be used. Do I use it like a regular Svelte app and ignore Blade completely? Can I build out components within Blade? Just not sure what the proper usage for this is. Thanks in advance and sorry for the dumb question.

**Comment by morpheus7CS** [comment]
Hey @nrthbound,

the package itself is intended as a helper for you to scaffold an initial Svelte setup, similar to how `php artisan ui vue` scaffolds the initial components for Vue inline components to be used in your Blade files.

Hope this helps. I'll close the issue, but if you have any subsequent questions, feel free to reopen.

Kind regards,
g
